### ISSUE TITLE
Hi! What part of the code represents the structure matrix U? 

### ISSUE THREAD

**Issue by phoebe11111111** [JHL-HUST/NAGphormer#7]
Hi! What part of the code represents the structure matrix U? Thanks!

**Comment by guangnianchenai** [comment]
Thank you for your attention. You can find the code for generating structure matrix in https://github.com/graphdeeplearning/graphtransformer/blob/main/data/molecules.py

**Comment by phoebe11111111** [comment]
Really appreciated for your answer!
