### ISSUE TITLE
Sorry to ask again, where is the connection between the feature matrix X and the structure matrix U in your paper (Equation 10) embodied in this code?

### ISSUE THREAD

**Issue by phoebe11111111** [JHL-HUST/NAGphormer#8]
Sorry to ask again, where is the connection between the feature matrix X and the structure matrix U in your paper (Equation 10) embodied in this code?

**Comment by guangnianchenai** [comment]
It is a pre-processing operation, not appearing in this code repository. You can combine the generated eigenvector matrix with the raw attribute feature matrix via the concatenation operation to obtain the input matrix of Hop2Token.
